import json

categories = [
    {
        "name": "Environment",
        "items": [
            "environmental impact",
            "carbon footprint",
            "renewable energy",
            "sustainable development",
            "climate change",
            "green technology",
            "natural resources",
            "biodiversity loss",
            "waste management",
            "ecological footprint",
            "air pollution",
            "water scarcity",
            "habitat destruction",
            "environmental degradation",
            "recycling program",
            "energy conservation",
            "global warming",
            "environmental policy",
            "pollution control",
            "wildlife protection",
            "ecosystem services",
            "carbon emission",
            "solar power",
            "wind turbine",
            "electric vehicle",
            "public transport",
            "environmental awareness",
            "climate crisis",
            "conservation effort",
            "fossil fuels",
            "soil erosion",
            "water treatment",
            "environmental legislation",
            "waste disposal",
            "pollution reduction",
            "habitat restoration",
            "climate adaptation",
            "environmental education",
            "green infrastructure",
            "organic farming",
            "renewable resource",
            "urban green space",
            "air quality",
            "water pollution",
            "environmental hazard",
            "consumer awareness",
            "carbon neutral",
            "energy efficiency",
            "climate mitigation",
            "nature reserve",
            "sustainable agriculture",
            "marine conservation"
        ]
    },
    {
        "name": "Education",
        "items": [
            "academic achievement",
            "higher education",
            "vocational training",
            "lifelong learning",
            "student motivation",
            "classroom environment",
            "teacher feedback",
            "exam preparation",
            "learning outcome",
            "educational reform",
            "distance learning",
            "curriculum design",
            "digital literacy",
            "school funding",
            "educational policy",
            "peer pressure",
            "school attendance",
            "classroom discipline",
            "language acquisition",
            "critical thinking",
            "research skills",
            "study habits",
            "educational inequality",
            "special education",
            "classroom interaction",
            "primary school",
            "secondary education",
            "adult education",
            "practical experience",
            "academic pressure",
            "learning environment",
            "teacher training",
            "literacy rate",
            "exam results",
            "academic support",
            "learning process",
            "scholarship program",
            "knowledge transfer",
            "student engagement",
            "educational technology",
            "extracurricular activity",
            "school curriculum",
            "educational standard",
            "inclusive education",
            "academic performance",
            "teacher shortage",
            "study materials",
            "online course",
            "learning community",
            "assessment method",
            "classroom resources",
            "student feedback"
        ]
    },
    {
        "name": "Technology",
        "items": [
            "digital transformation",
            "artificial intelligence",
            "data privacy",
            "cyber security",
            "mobile application",
            "smart devices",
            "cloud computing",
            "machine learning",
            "social media",
            "online platform",
            "digital economy",
            "virtual reality",
            "internet access",
            "technological innovation",
            "digital divide",
            "network infrastructure",
            "automation process",
            "software development",
            "user interface",
            "e-commerce trend",
            "big data",
            "tech industry",
            "wireless network",
            "electronic device",
            "tech startup",
            "digital content",
            "remote access",
            "information system",
            "technology adoption",
            "digital marketing",
            "data analytics",
            "smartphone usage",
            "cyber crime",
            "tech education",
            "digital skills",
            "high-speed internet",
            "wearable technology",
            "mobile payment",
            "online security",
            "digital footprint",
            "smart city",
            "automation technology",
            "innovation ecosystem",
            "technology sector",
            "data breach",
            "digital service",
            "virtual classroom",
            "online collaboration",
            "user experience",
            "digital infrastructure",
            "tech giant",
            "communication technology"
        ]
    },
    {
        "name": "Health",
        "items": [
            "public health",
            "mental health",
            "healthy lifestyle",
            "medical treatment",
            "health care",
            "chronic disease",
            "preventive medicine",
            "health insurance",
            "health awareness",
            "physical activity",
            "healthy diet",
            "medical research",
            "health service",
            "disease prevention",
            "health education",
            "patient care",
            "health centre",
            "nutritional value",
            "health outcome",
            "exercise routine",
            "medical facility",
            "health crisis",
            "health policy",
            "health system",
            "medical staff",
            "stress management",
            "health condition",
            "emergency care",
            "health screening",
            "nutrition program",
            "medical diagnosis",
            "health campaign",
            "medical procedure",
            "health behaviour",
            "illness prevention",
            "health improvement",
            "health promotion",
            "medical specialist",
            "healthy eating",
            "lifestyle choice",
            "community health",
            "health risk",
            "vaccination program",
            "health sector",
            "mental illness",
            "hospital staff",
            "patient recovery",
            "healthy habits",
            "health standard",
            "disease outbreak",
            "health assessment"
        ]
    },
    {
        "name": "Economy",
        "items": [
            "economic growth",
            "inflation rate",
            "fiscal policy",
            "consumer confidence",
            "global market",
            "job market",
            "financial crisis",
            "economic development",
            "trade deficit",
            "economic stability",
            "investment opportunity",
            "market demand",
            "stock market",
            "economic reform",
            "income inequality",
            "economic policy",
            "business sector",
            "financial institution",
            "housing market",
            "economic recovery",
            "tax revenue",
            "employment rate",
            "currency exchange",
            "economic forecast",
            "corporate tax",
            "labour market",
            "economic challenge",
            "small business",
            "economic indicator",
            "tax burden",
            "financial support",
            "export market",
            "economic strategy",
            "public spending",
            "economic sector",
            "monetary policy",
            "recession period",
            "consumer spending",
            "economic pressure",
            "business investment",
            "economic crisis",
            "corporate governance",
            "investment portfolio",
            "trade agreement",
            "economic planning",
            "economic research",
            "market competition",
            "financial market",
            "entrepreneurship development",
            "economic outlook"
        ]
    },
    {
        "name": "Society",
        "items": [
            "social awareness",
            "cultural diversity",
            "gender equality",
            "social cohesion",
            "community service",
            "family structure",
            "public opinion",
            "social welfare",
            "social behaviour",
            "cultural identity",
            "social issue",
            "social change",
            "urban population",
            "social interaction",
            "community development",
            "social responsibility",
            "social policy",
            "cultural heritage",
            "public transport",
            "social attitude",
            "social inequality",
            "cultural tradition",
            "community support",
            "social network",
            "family values",
            "social justice",
            "social environment",
            "urban lifestyle",
            "cultural exchange",
            "community project",
            "social norms",
            "social pressure",
            "social integration",
            "public awareness",
            "social development",
            "community centre",
            "social influence",
            "cultural event",
            "social institution",
            "community leader",
            "social problem",
            "cultural festival",
            "social participation",
            "social movement",
            "social identity",
            "cultural practice",
            "social programme",
            "public service",
            "social role",
            "community involvement"
        ]
    },
    {
        "name": "Government",
        "items": [
            "public policy",
            "government initiative",
            "political decision",
            "government funding",
            "public sector",
            "government regulation",
            "policy maker",
            "government agency",
            "tax reform",
            "government spending",
            "political stability",
            "public administration",
            "government program",
            "international relations",
            "government official",
            "policy review",
            "government strategy",
            "legislative process",
            "government report",
            "public service",
            "government budget",
            "political campaign",
            "government reform",
            "law enforcement",
            "government contract",
            "public consultation",
            "government authority",
            "electoral process",
            "government proposal",
            "public investment",
            "government debate",
            "government stance",
            "social policy",
            "government policy",
            "public expenditure",
            "government transparency",
            "political reform",
            "government coalition",
            "government negotiation",
            "public accountability",
            "government oversight",
            "government leadership",
            "policy framework",
            "government announcement",
            "public sector",
            "government minister",
            "government institution",
            "political agenda",
            "government statement"
        ]
    },
    {
        "name": "Work and Career",
        "items": [
            "job satisfaction",
            "career development",
            "workplace environment",
            "professional growth",
            "work experience",
            "career advancement",
            "job opportunity",
            "work-life balance",
            "job security",
            "career path",
            "professional skills",
            "employment opportunity",
            "workplace culture",
            "career change",
            "job market",
            "professional network",
            "career planning",
            "workplace stress",
            "job training",
            "professional development",
            "recruitment process",
            "career goal",
            "work performance",
            "employment condition",
            "job interview",
            "career success",
            "appraisal process",
            "workforce development",
            "career choice",
            "job position",
            "workplace safety",
            "employment law",
            "career transition",
            "job description",
            "workplace diversity",
            "career objective",
            "job promotion",
            "professional experience",
            "career advice",
            "employment benefits",
            "job application",
            "workplace policy",
            "career management",
            "business meeting",
            "employee motivation",
            "professional opportunity",
            "career achievement",
            "job performance",
            "workplace innovation",
            "career satisfaction",
            "employment rate"
        ]
    },
    {
        "name": "Crime and Law",
        "items": [
            "criminal justice",
            "law enforcement",
            "legal system",
            "crime prevention",
            "violent crime",
            "court hearing",
            "legal advice",
            "criminal record",
            "police investigation",
            "juvenile crime",
            "legal framework",
            "human rights",
            "prison sentence",
            "legal responsibility",
            "crime rate",
            "criminal behaviour",
            "court case",
            "legal reform",
            "public safety",
            "court verdict",
            "legal procedure",
            "crime scene",
            "domestic violence",
            "arrest warrant",
            "legal penalty",
            "criminal trial",
            "civil rights",
            "legal counsel",
            "crime investigation",
            "criminal offence",
            "judicial system",
            "legal dispute",
            "criminal sentence",
            "legal protection",
            "public prosecutor",
            "legal evidence",
            "crime report",
            "legal regulation",
            "criminal activity",
            "court decision",
            "legal obligation",
            "legal aid",
            "criminal law",
            "law enforcement officer",
            "legal document",
            "crime statistic",
            "legal prosecution",
            "police officer",
            "courtroom drama",
            "legal authority"
        ]
    },
    {
        "name": "Global Issues",
        "items": [
            "climate change",
            "global warming",
            "poverty reduction",
            "international aid",
            "sustainable development",
            "human rights",
            "globalisation process",
            "environmental crisis",
            "world poverty",
            "population growth",
            "carbon emissions",
            "global awareness",
            "international trade",
            "humanitarian crisis",
            "global economy",
            "natural disaster",
            "social inequality",
            "global health",
            "economic migration",
            "global cooperation",
            "cultural exchange",
            "global security",
            "climate policy",
            "renewable resources",
            "disaster relief",
            "global challenge",
            "water scarcity",
            "food security",
            "global crisis",
            "energy shortage",
            "global market",
            "global population",
            "international relations",
            "global agenda",
            "world leader",
            "global partnership",
            "environmental issue",
            "global perspective",
            "international community",
            "global impact",
            "global policy",
            "sustainable future",
            "global conflict",
            "climate action",
            "international agreement",
            "global infrastructure",
            "global development",
            "environmental protection",
            "global justice",
            "global trend"
        ]
    }
]

translation_map = {
    "environmental": "محیطی",
    "impact": "تأثیر",
    "carbon": "کربن",
    "footprint": "ردپا",
    "renewable": "تجدیدپذیر",
    "energy": "انرژی",
    "sustainable": "پایدار",
    "development": "توسعه",
    "climate": "آب و هوا",
    "change": "تغییر",
    "green": "سبز",
    "technology": "فناوری",
    "natural": "طبیعی",
    "resources": "منابع",
    "biodiversity": "تنوع زیستی",
    "loss": "از دست دادن",
    "waste": "پسماند",
    "management": "مدیریت",
    "ecological": "بوم‌شناختی",
    "air": "هوا",
    "pollution": "آلودگی",
    "water": "آب",
    "scarcity": "کمبود",
    "habitat": "زیستگاه",
    "destruction": "تخریب",
    "degradation": "فرسایش",
    "recycling": "بازیافت",
    "program": "برنامه",
    "conservation": "حفاظت",
    "global": "جهانی",
    "warming": "گرمایش",
    "policy": "سیاست",
    "control": "کنترل",
    "wildlife": "حیات‌وحش",
    "protection": "حفاظت",
    "ecosystem": "اکوسیستم",
    "services": "خدمات",
    "emission": "انتشار",
    "solar": "خورشیدی",
    "power": "قدرت",
    "wind": "باد",
    "turbine": "توربین",
    "electric": "الکتریکی",
    "vehicle": "وسیله‌نقلیه",
    "public": "عمومی",
    "transport": "حمل و نقل",
    "awareness": "آگاهی",
    "crisis": "بحران",
    "effort": "تلاش",
    "fossil": "فسیلی",
    "fuels": "سوخت‌ها",
    "soil": "خاک",
    "erosion": "فرسایش",
    "treatment": "درمان",
    "legislation": "قوانین",
    "disposal": "دفع",
    "reduction": "کاهش",
    "restoration": "بازسازی",
    "adaptation": "سازگاری",
    "education": "آموزش",
    "infrastructure": "زیرساخت",
    "organic": "ارگانیک",
    "farming": "کشاورزی",
    "urban": "شهری",
    "green": "سبز",
    "space": "فضا",
    "quality": "کیفیت",
    "hazard": "خطر",
    "consumer": "مصرف‌کننده",
    "neutral": "خنثی",
    "efficiency": "کارآیی",
    "mitigation": "کاهش",
    "nature": "طبیعت",
    "reserve": "پناهگاه",
    "agriculture": "کشاورزی",
    "marine": "دریایی",
    "health": "سلامت",
    "medical": "پزشکی",
    "treatment": "درمان",
    "care": "مراقبت",
    "chronic": "مزمن",
    "disease": "بیماری",
    "preventive": "پیشگیرانه",
    "insurance": "بیمه",
    "physical": "بدنی",
    "activity": "فعالیت",
    "diet": "رژیم غذایی",
    "research": "پژوهش",
    "service": "خدمات",
    "disease": "بیماری",
    "patient": "بیمار",
    "centre": "مرکز",
    "nutritional": "تغذیه‌ای",
    "value": "ارزش",
    "exercise": "تمرین",
    "facility": "تاسیسات",
    "policy": "سیاست",
    "system": "سیستم",
    "staff": "پرسنل",
    "stress": "استرس",
    "condition": "شرایط",
    "emergency": "اورژانسی",
    "screening": "غربالگری",
    "nutrition": "تغذیه",
    "programme": "برنامه",
    "campaign": "کمپین",
    "procedure": "روند",
    "behaviour": "رفتار",
    "illness": "بیماری",
    "promotion": " ترویج",
    "specialist": "متخصص",
    "eating": "خوردن",
    "choice": "انتخاب",
    "community": "جامعه",
    "risk": "خطر",
    "vaccination": "واکسیناسیون",
    "sector": "بخش",
    "hospital": "بیمارستان",
    "recovery": "بازیابی",
    "habit": "عادت",
    "standard": "استاندارد",
    "outbreak": "شیوع",
    "assessment": "ارزیابی",
    "academic": "علمی",
    "achievement": "دستاورد",
    "higher": "عالی",
    "education": "آموزش",
    "vocational": "فنی‌وحرفه‌ای",
    "training": "آموزش",
    "lifelong": "همیشگی",
    "learning": "یادگیری",
    "student": "دانش‌آموز",
    "motivation": "انگیزه",
    "classroom": "کلاس",
    "environment": "محیط",
    "teacher": "معلم",
    "feedback": "بازخورد",
    "exam": "امتحان",
    "preparation": "آمادگی",
    "learning": "یادگیری",
    "outcome": "نتیجه",
    "reform": "اصلاح",
    "distance": "دور",
    "curriculum": "برنامه درسی",
    "design": "طراحی",
    "digital": "دیجیتال",
    "literacy": "سواد",
    "school": "مدرسه",
    "funding": "تأمین مالی",
    "policy": "سیاست",
    "peer": "همتا",
    "pressure": "فشار",
    "attendance": "حضور",
    "discipline": "انضباط",
    "language": "زبان",
    "acquisition": "کسب",
    "critical": "انتقادی",
    "thinking": "تفکر",
    "research": "پژوهش",
    "skills": "مهارت‌ها",
    "study": "مطالعه",
    "habits": "عادات",
    "inequality": "نابرابری",
    "special": "خاص",
    "interaction": "تعامل",
    "primary": "ابتدایی",
    "secondary": "دبیرستانی",
    "adult": "بزرگسال",
    "practical": "عملی",
    "experience": "تجربه",
    "pressure": "فشار",
    "teacher": "معلم",
    "training": "آموزش",
    "literacy": "سواد",
    "rate": "نرخ",
    "results": "نتایج",
    "support": "حمایت",
    "process": "فرآیند",
    "scholarship": "بورسیه",
    "knowledge": "دانش",
    "transfer": "انتقال",
    "engagement": "درگیری",
    "technology": "فناوری",
    "extracurricular": "فوق برنامه",
    "activity": "فعالیت",
    "standard": "استاندارد",
    "inclusive": "شامل",
    "performance": "عملکرد",
    "materials": "مواد",
    "community": "جامعه",
    "assessment": "ارزیابی",
    "resources": "منابع",
    "feedback": "بازخورد",
    "opportunity": "فرصت",
    "digital": "دیجیتال",
    "transformation": "تحول",
    "artificial": "مصنوعی",
    "intelligence": "هوش",
    "data": "داده",
    "privacy": "حریم خصوصی",
    "cyber": "سایبری",
    "security": "امنیت",
    "mobile": "موبایل",
    "application": "اپلیکیشن",
    "smart": "هوشمند",
    "devices": "دستگاه‌ها",
    "cloud": "ابری",
    "computing": "محاسبات",
    "machine": "ماشین",
    "learning": "یادگیری",
    "social": "اجتماعی",
    "media": "رسانه‌ها",
    "online": "آنلاین",
    "platform": "سکو",
    "economy": "اقتصاد",
    "virtual": "مجازی",
    "reality": "واقعیت",
    "internet": "اینترنت",
    "access": "دسترسی",
    "technological": "فناوری",
    "innovation": "نوآوری",
    "divide": "شکاف",
    "network": "شبکه",
    "infrastructure": "زیرساخت",
    "automation": "خودکارسازی",
    "software": "نرم‌افزار",
    "development": "توسعه",
    "user": "کاربر",
    "interface": "رابط",
    "e-commerce": "تجارت الکترونیک",
    "trend": "روند",
    "big": "بزرگ",
    "industry": "صنعت",
    "wireless": "بی‌سیم",
    "wireless": "بی‌سیم",
    "electronic": "الکترونیکی",
    "startup": "استارتاپ",
    "content": "محتوا",
    "remote": "دور",
    "information": "اطلاعات",
    "system": "سیستم",
    "adoption": "پذیرش",
    "marketing": "بازاریابی",
    "analytics": "تحلیل",
    "smartphone": "گوشی هوشمند",
    "usage": "استفاده",
    "crime": "جرم",
    "education": "آموزش",
    "skills": "مهارت‌ها",
    "high-speed": "پُرسرعت",
    "wearable": "پوشیدنی",
    "payment": "پرداخت",
    "security": "امنیت",
    "footprint": "ردپا",
    "city": "شهر",
    "technology": "فناوری",
    "ecosystem": "اکوسیستم",
    "sector": "بخش",
    "breach": "نقض",
    "service": "خدمات",
    "collaboration": "همکاری",
    "experience": "تجربه",
    "infrastructure": "زیرساخت",
    "giant": "غول",
    "communication": "ارتباطات",
    "public": "عمومی",
    "policy": "سیاست",
    "initiative": "ابتکار",
    "political": "سیاسی",
    "decision": "تصمیم",
    "funding": "تأمین مالی",
    "sector": "بخش",
    "regulation": "مقررات",
    "maker": "سازنده",
    "agency": "سازمان",
    "tax": "مالیات",
    "spending": "هزینه",
    "stability": "ثبات",
    "administration": "اداره",
    "program": "برنامه",
    "international": "بین‌المللی",
    "relations": "روابط",
    "official": "رسمی",
    "review": "بازبینی",
    "strategy": "استراتژی",
    "legislative": "قانون‌گذاری",
    "process": "فرآیند",
    "report": "گزارش",
    "service": "خدمات",
    "budget": "بودجه",
    "campaign": "کمپین",
    "reform": "اصلاح",
    "law": "قانون",
    "enforcement": "اجرا",
    "contract": "قرارداد",
    "consultation": "مشاوره",
    "authority": "اختیار",
    "electoral": "انتخاباتی",
    "proposal": "پیشنهاد",
    "investment": "سرمایه‌گذاری",
    "debate": "مناظره",
    "stance": "موضع",
    "transparency": "شفافیت",
    "coalition": "ائتلاف",
    "negotiation": "مذاکره",
    "accountability": "پاسخگویی",
    "oversight": "نظارت",
    "leadership": "رهبری",
    "framework": "چارچوب",
    "announcement": "اعلام",
    "minister": "وزیر",
    "institution": "نهاد",
    "agenda": "دستور کار",
    "statement": "بیانیه",
    "career": "حرفه",
    "development": "توسعه",
    "workplace": "محیط کار",
    "professional": "حرفه‌ای",
    "growth": "رشد",
    "experience": "تجربه",
    "advancement": "پیشرفت",
    "opportunity": "فرصت",
    "life": "زندگی",
    "balance": "تعادل",
    "security": "امنیت",
    "path": "مسیر",
    "skills": "مهارت‌ها",
    "opportunity": "فرصت",
    "culture": "فرهنگ",
    "change": "تغییر",
    "network": "شبکه",
    "planning": "برنامه‌ریزی",
    "stress": "استرس",
    "training": "آموزش",
    "development": "توسعه",
    "recruitment": "استخدام",
    "goal": "هدف",
    "performance": "عملکرد",
    "condition": "شرایط",
    "interview": "مصاحبه",
    "success": "موفقیت",
    "appraisal": "ارزیابی",
    "workforce": "نیروی کار",
    "choice": "انتخاب",
    "position": "موقعیت",
    "safety": "ایمنی",
    "law": "قانون",
    "transition": "انتقال",
    "description": "شرح",
    "diversity": "تنوع",
    "objective": "هدف",
    "promotion": "ترفیع",
    "opportunity": "فرصت",
    "achievement": "دستاورد",
    "application": "درخواست",
    "innovation": "نوآوری",
    "management": "مدیریت",
    "rate": "نرخ",
    "criminal": "جنایی",
    "justice": "دادگستری",
    "enforcement": "اجرایی",
    "legal": "قانونی",
    "system": "سیستم",
    "prevention": "پیشگیری",
    "violent": "خشونت‌آمیز",
    "court": "دادگاه",
    "hearing": "شنوایی",
    "advice": "مشاوره",
    "record": "سابقه",
    "investigation": "تحقیق",
    "juvenile": "نوجوان",
    "framework": "چارچوب",
    "human": "انسانی",
    "rights": "حقوق",
    "prison": "زندان",
    "sentence": "حکم",
    "responsibility": "مسئولیت",
    "rate": "نرخ",
    "behaviour": "رفتار",
    "case": "پرونده",
    "reform": "اصلاح",
    "safety": "ایمنی",
    "verdict": "حکم",
    "procedure": "روند",
    "scene": "صحنه",
    "domestic": "خانگی",
    "violence": "خشونت",
    "arrest": "دستگیری",
    "warrant": "احضاریه",
    "penalty": "مجازات",
    "trial": "محاکمه",
    "civil": "مدنی",
    "counsel": "وکیل",
    "investigation": "تحقیق",
    "offence": "جرم",
    "judicial": "قضایی",
    "dispute": "اختلاف",
    "sentence": "حکم",
    "protection": "حفاظت",
    "prosecutor": "دادستان",
    "evidence": "مدارک",
    "report": "گزارش",
    "regulation": "مقررات",
    "activity": "فعالیت",
    "decision": "تصمیم",
    "obligation": "وظیفه",
    "aid": "کمک",
    "law": "قانون",
    "officer": "افسر",
    "document": "سند",
    "statistic": "آمار",
    "prosecution": "تعقیب قضایی",
    "authority": "اختیار",
    "climate": "آب و هوا",
    "warming": "گرمایش",
    "poverty": "فقر",
    "reduction": "کاهش",
    "international": "بین‌المللی",
    "aid": "کمک",
    "humanitarian": "انسان‌دوستانه",
    "world": "جهان",
    "population": "جمعیت",
    "emissions": "انتشارها",
    "awareness": "آگاهی",
    "trade": "تجارت",
    "humanitarian": "انسان‌دوستانه",
    "economy": "اقتصاد",
    "disaster": "فاجعه",
    "inequality": "نابرابری",
    "migration": "مهاجرت",
    "cooperation": "همکاری",
    "security": "امنیت",
    "policy": "سیاست",
    "resources": "منابع",
    "relief": "کمک‌رسانی",
    "challenge": "چالش",
    "scarcity": "کمبود",
    "food": "غذا",
    "shortage": "کمبود",
    "agenda": "دستور کار",
    "leader": "رهبر",
    "partnership": "شراکت",
    "issue": "مسئله",
    "perspective": "دیدگاه",
    "community": "جامعه",
    "impact": "تأثیر",
    "future": "آینده",
    "conflict": "تعارض",
    "action": "اقدام",
    "agreement": "توافق",
    "infrastructure": "زیرساخت",
    "protection": "حفاظت",
    "justice": "عدالت",
    "trend": "روند"
}

levels = ["B2", "C1"]

example_templates = {
    "Environment": [
        "A comprehensive {phrase} policy can improve city life and reduce long-term damage.",
        "Governments should invest in {phrase} to protect the natural environment.",
        "Public awareness of {phrase} helps students write stronger arguments in essays.",
        "An IELTS essay on {phrase} can argue that regulation is essential for sustainability.",
        "Experts agree that {phrase} is a key objective in modern environmental policy."
    ],
    "Education": [
        "Modern classrooms need a better {phrase} to support creative thinking.",
        "Many studies show that {phrase} improves student achievement in higher education.",
        "A controversial issue is whether {phrase} should be funded by the state.",
        "In IELTS writing, you can discuss how {phrase} shapes future generations.",
        "Governments are under pressure to reform {phrase} in public schools."
    ],
    "Technology": [
        "Rapid advances in {phrase} affect both employers and private individuals.",
        "One major IELTS topic is whether {phrase} creates more benefits than risks.",
        "Companies investing in {phrase} often outperform their rivals.",
        "It is important to regulate {phrase} to protect consumer rights.",
        "Students should learn how {phrase} influences the modern workplace."
    ],
    "Health": [
        "Good {phrase} habits can reduce healthcare costs and improve quality of life.",
        "Policymakers often debate whether {phrase} deserves more public funding.",
        "An essay might examine the impact of {phrase} on community wellbeing.",
        "Public campaigns about {phrase} can change long-term health behaviour.",
        "Health experts believe {phrase} should be part of every national plan."
    ],
    "Economy": [
        "Analysts warn that weak {phrase} may prolong economic instability.",
        "Careful planning around {phrase} can support sustainable growth.",
        "Many proposals focus on how to boost {phrase} after a crisis.",
        "An IELTS task could ask whether {phrase} is the key to prosperity.",
        "Experts recommend better regulation of {phrase} to protect consumers."
    ],
    "Society": [
        "Increasing {phrase} can help reduce social tensions in urban areas.",
        "Some people argue that {phrase} is essential for a fair society.",
        "A strong {phrase} encourages citizens to support each other.",
        "Modern media often shape public views on {phrase} topics.",
        "Community leaders promote {phrase} as part of social development."
    ],
    "Government": [
        "A balanced {phrase} is vital for long-term national stability.",
        "Public debate often centres on whether {phrase} is effective enough.",
        "An IELTS essay can analyse how {phrase} affects everyday citizens.",
        "Experts recommend transparent {phrase} to avoid corruption.",
        "The success of a democracy depends on strong {phrase}."
    ],
    "Work and Career": [
        "Improving {phrase} is a common theme in workplace reform essays.",
        "Young professionals often seek better {phrase} in competitive industries.",
        "A study showed that strong {phrase} boosts employee retention.",
        "Policies that support {phrase} help people balance work and family.",
        "Employers must recognise the value of {phrase} in the modern economy."
    ],
    "Crime and Law": [
        "The government should strengthen {phrase} to protect vulnerable citizens.",
        "An IELTS task may ask if improving {phrase} reduces urban crime.",
        "Researchers argue that fair {phrase} is essential for trust in society.",
        "Some critics believe that {phrase} needs more funding and reform.",
        "A strong {phrase} framework helps prevent serious offences."
    ],
    "Global Issues": [
        "International cooperation on {phrase} is becoming increasingly urgent.",
        "Many experts say that {phrase} requires a global response.",
        "An essay could explore whether {phrase} is the responsibility of rich nations.",
        "This century faces new challenges from {phrase} and its social costs.",
        "Policymakers must address {phrase} in sustainable development plans."
    ]
}

translation_cache = {}


def translate_phrase(phrase):
    if phrase in translation_cache:
        return translation_cache[phrase]
    parts = phrase.split()
    translated = []
    for part in parts:
        key = part.lower()
        if key in translation_map:
            translated.append(translation_map[key])
        else:
            translated.append(part)
    result = " ".join(translated)
    result = result.replace("  ", " ").strip()
    result = result.replace("_", " ")
    result = result.replace("-", " ")
    translation_cache[phrase] = result
    return result


def make_example(phrase, category):
    template = example_templates[category][hash(phrase) % len(example_templates[category])]
    sentence = template.format(phrase=phrase)
    return sentence

cards = []
next_id = 1
for category in categories:
    for phrase in category["items"]:
        cards.append({
            "id": next_id,
            "english": phrase,
            "translation": translate_phrase(phrase),
            "pronunciation": "/{}/".format(phrase.replace(" ", " ")),
            "example": make_example(phrase, category["name"]),
            "exampleTranslation": translate_phrase(phrase) + " در این جمله نشان می‌دهد که ...",
            "level": levels[next_id % 2],
            "category": category["name"]
        })
        next_id += 1

with open("src/data/collocations.json", "w", encoding="utf-8") as f:
    json.dump(cards, f, ensure_ascii=False, indent=2)

print(f"Generated {len(cards)} collocations")
